namespace Stoat.Services.Utils;

/// <summary>
/// Information about a country.
/// </summary>
public class CountryInfo
{
    /// <summary>
    /// ISO 3166-1 alpha-2 country code.
    /// </summary>
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// Country name in English.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Display string combining code and name.
    /// </summary>
    public string DisplayName => $"{Code} - {Name}";

    public override string ToString() => DisplayName;
}

/// <summary>
/// Helper class for ISO 3166-1 country codes.
/// </summary>
public static class CountryHelper
{
    private static readonly Lazy<IReadOnlyList<CountryInfo>> _countries = new(LoadCountries);

    /// <summary>
    /// Gets the list of countries sorted by name.
    /// </summary>
    public static IReadOnlyList<CountryInfo> GetCountries() => _countries.Value;

    /// <summary>
    /// Gets a country by its code.
    /// </summary>
    public static CountryInfo? GetCountryByCode(string code)
    {
        return _countries.Value.FirstOrDefault(c => c.Code.Equals(code, StringComparison.OrdinalIgnoreCase));
    }

    private static IReadOnlyList<CountryInfo> LoadCountries()
    {
        // ISO 3166-1 alpha-2 codes with country names
        var countries = new List<CountryInfo>
        {
            new() { Code = "AD", Name = "Andorra" },
            new() { Code = "AE", Name = "United Arab Emirates" },
            new() { Code = "AF", Name = "Afghanistan" },
            new() { Code = "AG", Name = "Antigua and Barbuda" },
            new() { Code = "AI", Name = "Anguilla" },
            new() { Code = "AL", Name = "Albania" },
            new() { Code = "AM", Name = "Armenia" },
            new() { Code = "AO", Name = "Angola" },
            new() { Code = "AQ", Name = "Antarctica" },
            new() { Code = "AR", Name = "Argentina" },
            new() { Code = "AS", Name = "American Samoa" },
            new() { Code = "AT", Name = "Austria" },
            new() { Code = "AU", Name = "Australia" },
            new() { Code = "AW", Name = "Aruba" },
            new() { Code = "AX", Name = "Aland Islands" },
            new() { Code = "AZ", Name = "Azerbaijan" },
            new() { Code = "BA", Name = "Bosnia and Herzegovina" },
            new() { Code = "BB", Name = "Barbados" },
            new() { Code = "BD", Name = "Bangladesh" },
            new() { Code = "BE", Name = "Belgium" },
            new() { Code = "BF", Name = "Burkina Faso" },
            new() { Code = "BG", Name = "Bulgaria" },
            new() { Code = "BH", Name = "Bahrain" },
            new() { Code = "BI", Name = "Burundi" },
            new() { Code = "BJ", Name = "Benin" },
            new() { Code = "BL", Name = "Saint Barthelemy" },
            new() { Code = "BM", Name = "Bermuda" },
            new() { Code = "BN", Name = "Brunei Darussalam" },
            new() { Code = "BO", Name = "Bolivia" },
            new() { Code = "BQ", Name = "Bonaire, Sint Eustatius and Saba" },
            new() { Code = "BR", Name = "Brazil" },
            new() { Code = "BS", Name = "Bahamas" },
            new() { Code = "BT", Name = "Bhutan" },
            new() { Code = "BV", Name = "Bouvet Island" },
            new() { Code = "BW", Name = "Botswana" },
            new() { Code = "BY", Name = "Belarus" },
            new() { Code = "BZ", Name = "Belize" },
            new() { Code = "CA", Name = "Canada" },
            new() { Code = "CC", Name = "Cocos (Keeling) Islands" },
            new() { Code = "CD", Name = "Congo, Democratic Republic" },
            new() { Code = "CF", Name = "Central African Republic" },
            new() { Code = "CG", Name = "Congo" },
            new() { Code = "CH", Name = "Switzerland" },
            new() { Code = "CI", Name = "Cote d'Ivoire" },
            new() { Code = "CK", Name = "Cook Islands" },
            new() { Code = "CL", Name = "Chile" },
            new() { Code = "CM", Name = "Cameroon" },
            new() { Code = "CN", Name = "China" },
            new() { Code = "CO", Name = "Colombia" },
            new() { Code = "CR", Name = "Costa Rica" },
            new() { Code = "CU", Name = "Cuba" },
            new() { Code = "CV", Name = "Cabo Verde" },
            new() { Code = "CW", Name = "Curacao" },
            new() { Code = "CX", Name = "Christmas Island" },
            new() { Code = "CY", Name = "Cyprus" },
            new() { Code = "CZ", Name = "Czechia" },
            new() { Code = "DE", Name = "Germany" },
            new() { Code = "DJ", Name = "Djibouti" },
            new() { Code = "DK", Name = "Denmark" },
            new() { Code = "DM", Name = "Dominica" },
            new() { Code = "DO", Name = "Dominican Republic" },
            new() { Code = "DZ", Name = "Algeria" },
            new() { Code = "EC", Name = "Ecuador" },
            new() { Code = "EE", Name = "Estonia" },
            new() { Code = "EG", Name = "Egypt" },
            new() { Code = "EH", Name = "Western Sahara" },
            new() { Code = "ER", Name = "Eritrea" },
            new() { Code = "ES", Name = "Spain" },
            new() { Code = "ET", Name = "Ethiopia" },
            new() { Code = "FI", Name = "Finland" },
            new() { Code = "FJ", Name = "Fiji" },
            new() { Code = "FK", Name = "Falkland Islands" },
            new() { Code = "FM", Name = "Micronesia" },
            new() { Code = "FO", Name = "Faroe Islands" },
            new() { Code = "FR", Name = "France" },
            new() { Code = "GA", Name = "Gabon" },
            new() { Code = "GB", Name = "United Kingdom" },
            new() { Code = "GD", Name = "Grenada" },
            new() { Code = "GE", Name = "Georgia" },
            new() { Code = "GF", Name = "French Guiana" },
            new() { Code = "GG", Name = "Guernsey" },
            new() { Code = "GH", Name = "Ghana" },
            new() { Code = "GI", Name = "Gibraltar" },
            new() { Code = "GL", Name = "Greenland" },
            new() { Code = "GM", Name = "Gambia" },
            new() { Code = "GN", Name = "Guinea" },
            new() { Code = "GP", Name = "Guadeloupe" },
            new() { Code = "GQ", Name = "Equatorial Guinea" },
            new() { Code = "GR", Name = "Greece" },
            new() { Code = "GS", Name = "South Georgia" },
            new() { Code = "GT", Name = "Guatemala" },
            new() { Code = "GU", Name = "Guam" },
            new() { Code = "GW", Name = "Guinea-Bissau" },
            new() { Code = "GY", Name = "Guyana" },
            new() { Code = "HK", Name = "Hong Kong" },
            new() { Code = "HM", Name = "Heard Island and McDonald Islands" },
            new() { Code = "HN", Name = "Honduras" },
            new() { Code = "HR", Name = "Croatia" },
            new() { Code = "HT", Name = "Haiti" },
            new() { Code = "HU", Name = "Hungary" },
            new() { Code = "ID", Name = "Indonesia" },
            new() { Code = "IE", Name = "Ireland" },
            new() { Code = "IL", Name = "Israel" },
            new() { Code = "IM", Name = "Isle of Man" },
            new() { Code = "IN", Name = "India" },
            new() { Code = "IO", Name = "British Indian Ocean Territory" },
            new() { Code = "IQ", Name = "Iraq" },
            new() { Code = "IR", Name = "Iran" },
            new() { Code = "IS", Name = "Iceland" },
            new() { Code = "IT", Name = "Italy" },
            new() { Code = "JE", Name = "Jersey" },
            new() { Code = "JM", Name = "Jamaica" },
            new() { Code = "JO", Name = "Jordan" },
            new() { Code = "JP", Name = "Japan" },
            new() { Code = "KE", Name = "Kenya" },
            new() { Code = "KG", Name = "Kyrgyzstan" },
            new() { Code = "KH", Name = "Cambodia" },
            new() { Code = "KI", Name = "Kiribati" },
            new() { Code = "KM", Name = "Comoros" },
            new() { Code = "KN", Name = "Saint Kitts and Nevis" },
            new() { Code = "KP", Name = "Korea, Democratic People's Republic" },
            new() { Code = "KR", Name = "Korea, Republic" },
            new() { Code = "KW", Name = "Kuwait" },
            new() { Code = "KY", Name = "Cayman Islands" },
            new() { Code = "KZ", Name = "Kazakhstan" },
            new() { Code = "LA", Name = "Lao People's Democratic Republic" },
            new() { Code = "LB", Name = "Lebanon" },
            new() { Code = "LC", Name = "Saint Lucia" },
            new() { Code = "LI", Name = "Liechtenstein" },
            new() { Code = "LK", Name = "Sri Lanka" },
            new() { Code = "LR", Name = "Liberia" },
            new() { Code = "LS", Name = "Lesotho" },
            new() { Code = "LT", Name = "Lithuania" },
            new() { Code = "LU", Name = "Luxembourg" },
            new() { Code = "LV", Name = "Latvia" },
            new() { Code = "LY", Name = "Libya" },
            new() { Code = "MA", Name = "Morocco" },
            new() { Code = "MC", Name = "Monaco" },
            new() { Code = "MD", Name = "Moldova" },
            new() { Code = "ME", Name = "Montenegro" },
            new() { Code = "MF", Name = "Saint Martin (French part)" },
            new() { Code = "MG", Name = "Madagascar" },
            new() { Code = "MH", Name = "Marshall Islands" },
            new() { Code = "MK", Name = "North Macedonia" },
            new() { Code = "ML", Name = "Mali" },
            new() { Code = "MM", Name = "Myanmar" },
            new() { Code = "MN", Name = "Mongolia" },
            new() { Code = "MO", Name = "Macao" },
            new() { Code = "MP", Name = "Northern Mariana Islands" },
            new() { Code = "MQ", Name = "Martinique" },
            new() { Code = "MR", Name = "Mauritania" },
            new() { Code = "MS", Name = "Montserrat" },
            new() { Code = "MT", Name = "Malta" },
            new() { Code = "MU", Name = "Mauritius" },
            new() { Code = "MV", Name = "Maldives" },
            new() { Code = "MW", Name = "Malawi" },
            new() { Code = "MX", Name = "Mexico" },
            new() { Code = "MY", Name = "Malaysia" },
            new() { Code = "MZ", Name = "Mozambique" },
            new() { Code = "NA", Name = "Namibia" },
            new() { Code = "NC", Name = "New Caledonia" },
            new() { Code = "NE", Name = "Niger" },
            new() { Code = "NF", Name = "Norfolk Island" },
            new() { Code = "NG", Name = "Nigeria" },
            new() { Code = "NI", Name = "Nicaragua" },
            new() { Code = "NL", Name = "Netherlands" },
            new() { Code = "NO", Name = "Norway" },
            new() { Code = "NP", Name = "Nepal" },
            new() { Code = "NR", Name = "Nauru" },
            new() { Code = "NU", Name = "Niue" },
            new() { Code = "NZ", Name = "New Zealand" },
            new() { Code = "OM", Name = "Oman" },
            new() { Code = "PA", Name = "Panama" },
            new() { Code = "PE", Name = "Peru" },
            new() { Code = "PF", Name = "French Polynesia" },
            new() { Code = "PG", Name = "Papua New Guinea" },
            new() { Code = "PH", Name = "Philippines" },
            new() { Code = "PK", Name = "Pakistan" },
            new() { Code = "PL", Name = "Poland" },
            new() { Code = "PM", Name = "Saint Pierre and Miquelon" },
            new() { Code = "PN", Name = "Pitcairn" },
            new() { Code = "PR", Name = "Puerto Rico" },
            new() { Code = "PS", Name = "Palestine" },
            new() { Code = "PT", Name = "Portugal" },
            new() { Code = "PW", Name = "Palau" },
            new() { Code = "PY", Name = "Paraguay" },
            new() { Code = "QA", Name = "Qatar" },
            new() { Code = "RE", Name = "Reunion" },
            new() { Code = "RO", Name = "Romania" },
            new() { Code = "RS", Name = "Serbia" },
            new() { Code = "RU", Name = "Russian Federation" },
            new() { Code = "RW", Name = "Rwanda" },
            new() { Code = "SA", Name = "Saudi Arabia" },
            new() { Code = "SB", Name = "Solomon Islands" },
            new() { Code = "SC", Name = "Seychelles" },
            new() { Code = "SD", Name = "Sudan" },
            new() { Code = "SE", Name = "Sweden" },
            new() { Code = "SG", Name = "Singapore" },
            new() { Code = "SH", Name = "Saint Helena" },
            new() { Code = "SI", Name = "Slovenia" },
            new() { Code = "SJ", Name = "Svalbard and Jan Mayen" },
            new() { Code = "SK", Name = "Slovakia" },
            new() { Code = "SL", Name = "Sierra Leone" },
            new() { Code = "SM", Name = "San Marino" },
            new() { Code = "SN", Name = "Senegal" },
            new() { Code = "SO", Name = "Somalia" },
            new() { Code = "SR", Name = "Suriname" },
            new() { Code = "SS", Name = "South Sudan" },
            new() { Code = "ST", Name = "Sao Tome and Principe" },
            new() { Code = "SV", Name = "El Salvador" },
            new() { Code = "SX", Name = "Sint Maarten (Dutch part)" },
            new() { Code = "SY", Name = "Syrian Arab Republic" },
            new() { Code = "SZ", Name = "Eswatini" },
            new() { Code = "TC", Name = "Turks and Caicos Islands" },
            new() { Code = "TD", Name = "Chad" },
            new() { Code = "TF", Name = "French Southern Territories" },
            new() { Code = "TG", Name = "Togo" },
            new() { Code = "TH", Name = "Thailand" },
            new() { Code = "TJ", Name = "Tajikistan" },
            new() { Code = "TK", Name = "Tokelau" },
            new() { Code = "TL", Name = "Timor-Leste" },
            new() { Code = "TM", Name = "Turkmenistan" },
            new() { Code = "TN", Name = "Tunisia" },
            new() { Code = "TO", Name = "Tonga" },
            new() { Code = "TR", Name = "Turkey" },
            new() { Code = "TT", Name = "Trinidad and Tobago" },
            new() { Code = "TV", Name = "Tuvalu" },
            new() { Code = "TW", Name = "Taiwan" },
            new() { Code = "TZ", Name = "Tanzania" },
            new() { Code = "UA", Name = "Ukraine" },
            new() { Code = "UG", Name = "Uganda" },
            new() { Code = "UM", Name = "United States Minor Outlying Islands" },
            new() { Code = "US", Name = "United States of America" },
            new() { Code = "UY", Name = "Uruguay" },
            new() { Code = "UZ", Name = "Uzbekistan" },
            new() { Code = "VA", Name = "Holy See" },
            new() { Code = "VC", Name = "Saint Vincent and the Grenadines" },
            new() { Code = "VE", Name = "Venezuela" },
            new() { Code = "VG", Name = "Virgin Islands, British" },
            new() { Code = "VI", Name = "Virgin Islands, U.S." },
            new() { Code = "VN", Name = "Viet Nam" },
            new() { Code = "VU", Name = "Vanuatu" },
            new() { Code = "WF", Name = "Wallis and Futuna" },
            new() { Code = "WS", Name = "Samoa" },
            new() { Code = "YE", Name = "Yemen" },
            new() { Code = "YT", Name = "Mayotte" },
            new() { Code = "ZA", Name = "South Africa" },
            new() { Code = "ZM", Name = "Zambia" },
            new() { Code = "ZW", Name = "Zimbabwe" }
        };

        return countries.OrderBy(c => c.Name).ToList().AsReadOnly();
    }
}
