<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets/Images/stoat-white.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Version>0.8.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.11" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.11" />
    <PackageReference Include="Avalonia.Skia" Version="11.3.11" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.4" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.1.4" />
    <PackageReference Include="Avalonia.Win32" Version="11.3.11" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.11" />
    <PackageReference Include="HeroIcons.Avalonia" Version="1.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.9.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stoat.Core\Stoat.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
      <AvaloniaResource Include="Assets/Images/**" />
      <AvaloniaResource Include="Assets/Localization/*.json" />
  </ItemGroup>

</Project>
